---
- name: Setup Ubuntu Development Environment
  hosts: localhost
  become: true

  roles:
    - timeshift_backup
    - cli_utilities
    - chrome
    - docker
    - elixir_asdf
    - lua
    - ghostty
    - vscode
    - codex
    - dotnet
