---
- name: Install Ghostty dependencies
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Check if Ghostty is installed
  shell: command -v ghostty
  args:
    executable: /bin/bash
  register: ghostty_check
  changed_when: false
  failed_when: false
  become: false

- name: Install Ghostty
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh)"
  args:
    executable: /bin/bash
  when: ghostty_check.rc != 0
